# Generated by Django 5.2.12 on 2026-03-29 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('environment', models.CharField(blank=True, max_length=120)),
                ('database_vendor', models.CharField(max_length=40)),
                ('database_name', models.CharField(blank=True, max_length=120)),
                ('collector_version', models.CharField(default='foundation-v1', max_length=40)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('degraded', 'Degraded'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryStatSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queryid', models.CharField(blank=True, max_length=128)),
                ('query_text_normalized', models.TextField()),
                ('calls', models.BigIntegerField(default=0)),
                ('total_exec_time', models.FloatField(default=0)),
                ('mean_exec_time', models.FloatField(default=0)),
                ('min_exec_time', models.FloatField(default=0)),
                ('max_exec_time', models.FloatField(default=0)),
                ('rows', models.BigIntegerField(default=0)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_stats', to='db_monitor.statssnapshot')),
            ],
            options={
                'ordering': ['-total_exec_time', '-calls'],
            },
        ),
        migrations.CreateModel(
            name='IndexStatSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(max_length=120)),
                ('table_name', models.CharField(max_length=120)),
                ('index_name', models.CharField(max_length=120)),
                ('idx_scan', models.BigIntegerField(default=0)),
                ('index_size_bytes', models.BigIntegerField(default=0)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_stats', to='db_monitor.statssnapshot')),
            ],
            options={
                'ordering': ['idx_scan', '-index_size_bytes'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('severity', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('object_type', models.CharField(blank=True, max_length=64)),
                ('object_name', models.CharField(blank=True, max_length=180)),
                ('evidence_json', models.JSONField(blank=True, default=dict)),
                ('is_resolved', models.BooleanField(default=False)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='db_monitor.statssnapshot')),
            ],
            options={
                'ordering': ['severity', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ActivitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('state', models.CharField(blank=True, max_length=64)),
                ('wait_event_type', models.CharField(blank=True, max_length=64)),
                ('wait_event', models.CharField(blank=True, max_length=128)),
                ('query', models.TextField(blank=True)),
                ('duration_ms', models.FloatField(default=0)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='db_monitor.statssnapshot')),
            ],
            options={
                'ordering': ['-duration_ms', 'pid'],
            },
        ),
        migrations.CreateModel(
            name='TableStatSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(max_length=120)),
                ('table_name', models.CharField(max_length=120)),
                ('seq_scan', models.BigIntegerField(default=0)),
                ('idx_scan', models.BigIntegerField(default=0)),
                ('n_live_tup', models.BigIntegerField(default=0)),
                ('n_dead_tup', models.BigIntegerField(default=0)),
                ('vacuum_count', models.BigIntegerField(default=0)),
                ('autovacuum_count', models.BigIntegerField(default=0)),
                ('analyze_count', models.BigIntegerField(default=0)),
                ('autoanalyze_count', models.BigIntegerField(default=0)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_stats', to='db_monitor.statssnapshot')),
            ],
            options={
                'ordering': ['-seq_scan', '-n_live_tup'],
            },
        ),
    ]
